version: '3'

services:
  algod:
    container_name: algorand-sandbox-algod
    image: algorand/algod:latest
    ports:
      - "4001:4001"  # algod API
      - "4002:4002"  # kmd API
    environment:
      - START_KMD=1
      - TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - ADMIN_TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    volumes:
      - algod-data:/algod/data

  indexer:
    container_name: algorand-sandbox-indexer
    image: algorand/indexer:latest
    ports:
      - "8980:8980"  # indexer API
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=indexer-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=algorand
      - POSTGRES_PASSWORD=algorand
      - POSTGRES_DB=indexer
    depends_on:
      - indexer-db
      - algod

  indexer-db:
    container_name: algorand-sandbox-postgres
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=algorand
      - POSTGRES_PASSWORD=algorand
      - POSTGRES_DB=indexer
    volumes:
      - indexer-db-data:/var/lib/postgresql/data

volumes:
  algod-data:
  indexer-db-data:
